/**
 * gen-splash.mjs — iOS PWA 네이티브 런치 스플래시(apple-touch-startup-image) 생성.
 *
 * 왜: iOS 홈화면 PWA 는 아이콘 탭 후 웹 뷰가 로드되기 전, apple-touch-startup-image
 * 가 없으면 검은 화면을 띄운다(사장님 리포트 2026-07-13). manifest background_color
 * 는 iOS 런치에 신뢰성 있게 안 먹힘. 그래서 기기 해상도별로 "크림(#FAF9F5) 배경 +
 * 중앙 로고" PNG 를 미리 만들어 심는다 → 웹 스플래시(.ft-splash, 같은 크림+중앙 로고)
 * 와 이음새 없이 이어진다.
 *
 * 배경색 #FAF9F5 = :root --bg (globals.css) = layout head 크리티컬 인라인 배경 →
 * 네이티브 런치 · 웹 첫 페인트 · 웹 스플래시 3중 일치.
 *
 * 로고 폭 = 210 * dpr px (= 웹 스플래시 .ft-splash__logo 의 210 CSS px 와 동일 배율).
 *
 * 산출물: public/splash/apple-splash-{W}-{H}.png 들 + lib/pwaSplash.generated.ts
 * (layout.tsx 가 import 해서 <link> 태그로 렌더 — 단일 소스, 수기 목록 drift 없음).
 *
 * 재생성: node scripts/gen-splash.mjs   (로고/색/기기 목록 바뀌면)
 */
import sharp from 'sharp'
import { mkdir, writeFile } from 'node:fs/promises'
import path from 'node:path'

const CREAM = { r: 0xfa, g: 0xf9, b: 0xf5, alpha: 1 } // #FAF9F5
const LOGO = 'public/logo-ink.png'
const OUT_DIR = 'public/splash'
const CSS_LOGO_W = 210

// [cssWidth, cssHeight, devicePixelRatio, label] — 세로(portrait) 기준.
// iOS 는 media query 가 정확히 일치해야 이미지를 쓰므로 논리 해상도(CSS px)로 명시.
const DEVICES = [
  // iPhone
  [320, 568, 2, 'iPhone SE(1)/5'],
  [375, 667, 2, 'iPhone 8/SE(2·3)'],
  [414, 736, 3, 'iPhone 8 Plus'],
  [375, 812, 3, 'iPhone X/XS/11 Pro/12·13 mini'],
  [414, 896, 2, 'iPhone XR/11'],
  [414, 896, 3, 'iPhone XS Max/11 Pro Max'],
  [390, 844, 3, 'iPhone 12/13/14'],
  [428, 926, 3, 'iPhone 12·13 Pro Max/14 Plus'],
  [393, 852, 3, 'iPhone 14 Pro/15/15 Pro/16'],
  [430, 932, 3, 'iPhone 15 Plus/15 Pro Max/16 Plus'],
  [402, 874, 3, 'iPhone 16 Pro'],
  [440, 956, 3, 'iPhone 16 Pro Max'],
  // iPad (customer 대비)
  [768, 1024, 2, 'iPad mini/Air/9.7'],
  [810, 1080, 2, 'iPad 10.2'],
  [820, 1180, 2, 'iPad Air 10.9'],
  [834, 1112, 2, 'iPad Pro 10.5'],
  [834, 1194, 2, 'iPad Pro 11'],
  [1024, 1366, 2, 'iPad Pro 12.9'],
]

await mkdir(OUT_DIR, { recursive: true })

const entries = []
for (const [cssW, cssH, dpr, label] of DEVICES) {
  const W = cssW * dpr
  const H = cssH * dpr
  const logoW = Math.round(CSS_LOGO_W * dpr)

  // 로고를 폭 기준으로 리사이즈(비율 유지) 후 정중앙 배치.
  const logoBuf = await sharp(LOGO).resize({ width: logoW }).png().toBuffer()
  const logoMeta = await sharp(logoBuf).metadata()
  const left = Math.round((W - logoW) / 2)
  const top = Math.round((H - logoMeta.height) / 2)

  const file = `apple-splash-${W}-${H}.png`
  await sharp({
    create: { width: W, height: H, channels: 4, background: CREAM },
  })
    .composite([{ input: logoBuf, left, top }])
    .png()
    .toFile(path.join(OUT_DIR, file))

  entries.push({
    media: `(device-width: ${cssW}px) and (device-height: ${cssH}px) and (-webkit-device-pixel-ratio: ${dpr}) and (orientation: portrait)`,
    href: `/splash/${file}`,
  })
  console.log('✓', file.padEnd(24), label)
}

const ts = `// AUTO-GENERATED by scripts/gen-splash.mjs — 수기 편집 금지.
// iOS PWA 네이티브 런치 스플래시(apple-touch-startup-image) 목록. layout.tsx 가
// import 해 <link rel="apple-touch-startup-image"> 로 렌더한다. 재생성:
//   node scripts/gen-splash.mjs
export const APPLE_SPLASH: { media: string; href: string }[] = ${JSON.stringify(
  entries,
  null,
  2,
)}
`
await writeFile('lib/pwaSplash.generated.ts', ts)
console.log(`\nwrote lib/pwaSplash.generated.ts — ${entries.length} entries`)
